name: Install Terraform, Show Version, and List Files
on:
  push:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.5.3

    - name: Show Terraform version and list files
      run: |
        terraform version
        ls -R
        
    - name: Configure AWS credentials
      run: |
        echo "AWS_ACCESS_KEY_ID=your_aws_access_key" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=your_aws_secret_key" >> $GITHUB_ENV
        
    - name: Initialize Terraform
      run: terraform init
      
    - name: Apply Terraform changes
      run: terraform apply -auto-approve

